### ISSUE TITLE
Loading packages not working

### ISSUE THREAD

**Issue by jtr13** [r-wasm/quarto-drop#12]
First of all, thanks for a great extension!

This example isn't working for me:
```
format:
  revealjs:
    drop:
      engine: webr
      webr:
        packages:
          - ggplot2
          - dplyr
```

When I try to make a plot with **ggplot2** I get:
`Error in ggplot(mtcars, aes(wt, mpg)) : could not find function "ggplot"`
